package com.redhat.impacto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Calculo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Double scoreOrigem;
   private Double scoreDestino;
   private java.lang.String segmentoDestino;
   private java.lang.String ratingDestino;
   private java.lang.String setorOrigem;
   private Double pagamento;

   private java.util.List<com.redhat.impacto.Recebimento> recebimentos;

   private java.lang.Double _totalReceb;

   private java.lang.Double _pesoRelac;

   private java.lang.Double _impacto;

   private java.lang.Double _fatorAbsorcao;

   private java.lang.Double _fatorImpacto;

   private java.lang.Double _scoreFinal;

   public Calculo()
   {
   }

   public java.lang.String getSegmentoDestino()
   {
      return this.segmentoDestino;
   }

   public void setSegmentoDestino(java.lang.String segmentoDestino)
   {
      this.segmentoDestino = segmentoDestino;
   }

   public java.lang.String getRatingDestino()
   {
      return this.ratingDestino;
   }

   public void setRatingDestino(java.lang.String ratingDestino)
   {
      this.ratingDestino = ratingDestino;
   }

   public java.lang.String getSetorOrigem()
   {
      return this.setorOrigem;
   }

   public void setSetorOrigem(java.lang.String setorOrigem)
   {
      this.setorOrigem = setorOrigem;
   }

   public java.util.List<com.redhat.impacto.Recebimento> getRecebimentos()
   {
      return this.recebimentos;
   }

   public void setRecebimentos(
         java.util.List<com.redhat.impacto.Recebimento> recebimentos)
   {
      this.recebimentos = recebimentos;
   }

   public java.lang.Double getScoreOrigem()
   {
      return this.scoreOrigem;
   }

   public void setScoreOrigem(java.lang.Double scoreOrigem)
   {
      this.scoreOrigem = scoreOrigem;
   }

   public java.lang.Double getScoreDestino()
   {
      return this.scoreDestino;
   }

   public void setScoreDestino(java.lang.Double scoreDestino)
   {
      this.scoreDestino = scoreDestino;
   }

   public java.lang.Double getPagamento()
   {
      return this.pagamento;
   }

   public void setPagamento(java.lang.Double pagamento)
   {
      this.pagamento = pagamento;
   }

   public java.lang.Double get_totalReceb()
   {
      return this._totalReceb;
   }

   public void set_totalReceb(java.lang.Double _totalReceb)
   {
      this._totalReceb = _totalReceb;
   }

   public java.lang.Double get_pesoRelac()
   {
      return this._pesoRelac;
   }

   public void set_pesoRelac(java.lang.Double _pesoRelac)
   {
      this._pesoRelac = _pesoRelac;
   }

   public java.lang.Double get_impacto()
   {
      return this._impacto;
   }

   public void set_impacto(java.lang.Double _impacto)
   {
      this._impacto = _impacto;
   }

   public java.lang.Double get_fatorAbsorcao()
   {
      return this._fatorAbsorcao;
   }

   public void set_fatorAbsorcao(java.lang.Double _fatorAbsorcao)
   {
      this._fatorAbsorcao = _fatorAbsorcao;
   }

   public java.lang.Double get_fatorImpacto()
   {
      return this._fatorImpacto;
   }

   public void set_fatorImpacto(java.lang.Double _fatorImpacto)
   {
      this._fatorImpacto = _fatorImpacto;
   }

   public java.lang.Double get_scoreFinal()
   {
      return this._scoreFinal;
   }

   public void set_scoreFinal(java.lang.Double _scoreFinal)
   {
      this._scoreFinal = _scoreFinal;
   }

   public Calculo(java.lang.Double scoreOrigem, java.lang.Double scoreDestino,
         java.lang.String segmentoDestino, java.lang.String ratingDestino,
         java.lang.String setorOrigem, java.lang.Double pagamento,
         java.util.List<com.redhat.impacto.Recebimento> recebimentos,
         java.lang.Double _totalReceb, java.lang.Double _pesoRelac,
         java.lang.Double _impacto, java.lang.Double _fatorAbsorcao,
         java.lang.Double _fatorImpacto, java.lang.Double _scoreFinal)
   {
      this.scoreOrigem = scoreOrigem;
      this.scoreDestino = scoreDestino;
      this.segmentoDestino = segmentoDestino;
      this.ratingDestino = ratingDestino;
      this.setorOrigem = setorOrigem;
      this.pagamento = pagamento;
      this.recebimentos = recebimentos;
      this._totalReceb = _totalReceb;
      this._pesoRelac = _pesoRelac;
      this._impacto = _impacto;
      this._fatorAbsorcao = _fatorAbsorcao;
      this._fatorImpacto = _fatorImpacto;
      this._scoreFinal = _scoreFinal;
   }

}