package com.redhat.impacto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Calculo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double _totalReceb;

   private java.util.List<com.redhat.impacto.Recebimento> recebimentos;

   public Calculo()
   {
   }

   public java.lang.Double get_totalReceb()
   {
      return this._totalReceb;
   }

   public void set_totalReceb(java.lang.Double _totalReceb)
   {
      this._totalReceb = _totalReceb;
   }

   public java.util.List<com.redhat.impacto.Recebimento> getRecebimentos()
   {
      return this.recebimentos;
   }

   public void setRecebimentos(
         java.util.List<com.redhat.impacto.Recebimento> recebimentos)
   {
      this.recebimentos = recebimentos;
   }

   public Calculo(java.lang.Double _totalReceb,
         java.util.List<com.redhat.impacto.Recebimento> recebimentos)
   {
      this._totalReceb = _totalReceb;
      this.recebimentos = recebimentos;
   }

}