package com.redhat.impacto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Recebimento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String origem;
   private Double recebimento;

   public Recebimento()
   {
   }

   public java.lang.String getOrigem()
   {
      return this.origem;
   }

   public void setOrigem(java.lang.String origem)
   {
      this.origem = origem;
   }

   public java.lang.Double getRecebimento()
   {
      return this.recebimento;
   }

   public void setRecebimento(java.lang.Double recebimento)
   {
      this.recebimento = recebimento;
   }

   public Recebimento(java.lang.String origem, java.lang.Double recebimento)
   {
      this.origem = origem;
      this.recebimento = recebimento;
   }

}